apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Create the namespace for the management cluster
  - namespaces.yaml
  - configmap.yaml
# Install Cluster-sync components
  - build.yaml
  - workloads.yaml
