apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Create the namespace for the management cluster
  - namespaces.yaml
  - configmap.yaml
# Install Cluster-sync components
  - gotk-clusters.yaml
  - gotk-management.yaml

# Append all resources with the component name and version
commonLabels:
  lootbot.cloud/ComponentName: "workloads"
  lootbot.cloud/ComponentVersion: "v1.0.0"