# -------------------------------------------------------------
# Create The restricted PSP and RBAC for the management cluster
# -------------------------------------------------------------
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-baseline
  annotations:
  # This is necessary to prevent an error from the PodSecurityPolicy
  # even if we dont use seccomp annotations in our pods
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false 
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false        # <--- This is the default
  requiredDropCapabilities:
    - ALL                                       # <--- REQUIRED Drop all capabilities
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'                   # <--- Allow PVCs
  hostNetwork: false                            # <--- No host networking
  hostIPC: false                                # <--- No host IPC
  hostPID: false                                # <--- No host PID
  runAsUser:
    rule: 'MustRunAsNonRoot'                    # <--- Must run as non root
  seLinux:
    rule: 'RunAsAny'                            # <--- SELinux is not required
  supplementalGroups:
    rule: 'MustRunAs'                           # <--- Must run as a group
    ranges:
    - min: 1
      max: 65535
  fsGroup:                                      # <--- Must run as a group? 
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false                 # <--- No read only root filesystem
---
# Create the restricted-baseline ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-baseline
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted-baseline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted-baseline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-baseline
subjects: 
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:servicaccounts
  apiGroup: rbac.authorization.k8s.io
---