#------------------------------------------------
# cluster-security-component
# Responsible for deploying the Clusters PSP and RBAC security controls
#------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# ------------------------------------------------
# This is the PSP policy for the management cluster Kubernetes Version < v1.25
  - restricted-baseline.yaml  # <--- Applys restricted to all namespaces
  - privliged-baseline.yaml  # <--- Creates the privlived psp
  # Create the grouping of namespaces that will be privileged
  - privliged-namespaces.yaml # <--- Creates the privlived RBAC for kube-system and flux-system
  
# This is the PSA policy for the management cluster Kubernetes Version >= v1.25
#------------------------------------------------
  - pod-security-admission.yaml # <--- Sets the default policy to restricted and exempt kube-system and flux-system
  # Enforces at kubernetes version v1.25
# Append all resources with the component name and version
commonLabels:
  lootbot.cloud/ComponentName: "cluster-security"
  lootbot.cloud/ComponentVersion: "v1.0.0"