# -------------------------------------------------------------
# Create The privliged PSP and RBAC for the management cluster
# -------------------------------------------------------------
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privliged-baseline
  annotations:
  # This is necessary to prevent an error from the PodSecurityPolicy
  # even if we dont use seccomp annotations in our pods
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: true                            # <--- This is the default
  allowPrivilegeEscalation: true              # <--- This is the default
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'                          # <--- Run as any user
  seLinux:
    rule: 'RunAsAny'                          # <--- SELinux is not required
  supplementalGroups:
    rule: 'RunAsAny'                          # <--- Run as any group
  fsGroup:
    rule: 'RunAsAny'                          # <--- Run as any group
  readOnlyRootFilesystem: false
---
# Create the privliged-baseline ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privliged-baseline
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privliged-baseline