apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gotk-sync
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: gotk-sources
    namespace: flux-system
  path: ./management/flux-system
  # --- 
  prune: true
  # ---
  interval: 30m0s # Potential change to 60m0s
  timeout: 5m
  healthChecks: # <--- Perform health checks on all flux-system components
  # Source Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: source-controller
    namespace: flux-system
  # Kustomize Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: kustomize-controller
    namespace: flux-system
  # Helm Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: helm-controller
    namespace: flux-system