apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-component
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: components-production
    namespace: flux-system
  path: ./management/flux-system
  # --- 
  prune: true
  # ---
  interval: 10m0s
  timeout: 5m
  healthChecks: # <--- Perform health checks on all flux-system components
  # Source Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: source-controller
    namespace: flux-system
  # Kustomize Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: kustomize-controller
    namespace: flux-system
  # Helm Controller
  - apiVersion: apps/v1
    kind: Deployment
    name: helm-controller
    namespace: flux-system