# ------------------------------------------------
# Create the namespace for flux sources
# This is the namespace flux will use to store all sources
# ------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  name: flux-sources
