#------------------------------------------------
# Components sync configuration
#------------------------------------------------
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gotk-sources
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    semver: 1.0.x
    # branch: main
  # secretRef:
  #   name: flux-system
  url: https://github.com/devbot-cloud/components.git
---
