#------------------------------------------------
# The Cluster-Security component is responsible for deploying the Clusters PSP and RBAC security controls
# The Cluster-Security component will deploy policy engines in the future such as OPA and Kyverno
#------------------------------------------------
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster-securtiy-component-git
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 10s
  url: ssh://git@github.com/devbot-cloud/components.git # <--- Change this to the repo your currently in
  ignore: |
    # Exclude Everything
    /*
    # include cluster-securtiy component
    !/cluster-securtiy/
---
#------------------------------------------------
# This is the kustomize for the Clusters Security component
# The Security component contain the flux kustomizations
# This contains the psp and rbac for the management cluster
#------------------------------------------------
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-security-component
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system-component  # <--- Wait for the core Flux-system to be deployed
      namespace: flux-system
  interval: 1m0s
  path: ./cluster-security/v1.0.0/ # <--- Change this to the path to the security component
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-securtiy-component-git
    namespace: flux-system
  validation: server
  timeout: 5m
  # ---
  # Post build
  # Pull the Replacements from the ConfigMap cluster-env
  # This contains the SSH Path and Cluster Name
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
  # ---