apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-sources.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - gotk-security.yaml 
  - gotk-workloads.yaml

# Append all resources with the component name and version
commonLabels:
  lootbot.cloud/ComponentName: "management"
  lootbot.cloud/ComponentVersion: "v1.0.0"